import type { Attraction, AttrCategory } from "./types";

export const ATTR_CATS: AttrCategory[] = [
  { id: "all", label: "All Attractions" },
  { id: "theme-park", label: "Theme Parks" },
  { id: "museum", label: "Museums" },
  { id: "nature", label: "Nature & Zoo" },
  { id: "heritage", label: "Heritage" },
  { id: "family", label: "Family Fun" },
  { id: "experience", label: "Experiences" },
];

export const ALL_ATTRACTIONS: Attraction[] = [
  {
    id:"att-001", cat:"theme-park", featured:true,
    name:"Thorpe Park Resort",
    operator:"Merlin Entertainments",
    city:"Surrey", address:"Staines Rd, Chertsey, Surrey KT16 8PN",
    hours:"10:00–18:00 (Fri–Sun 10:00–21:00)", closedOn:"Mon–Thu (off-peak)",
    rating:4.3, reviews:62400,
    image:"https://images.unsplash.com/photo-1464059728276-d877187d61a9?w=900&h=500&fit=crop&auto=format",
    badge:"Summer Hours", badgeType:"new", color:"#f97316",
    highlights:["16 major thrill rides","Fright Nights (Oct)","THORPE SHARK Hotel","Island Eats food court","Free parking"],
    tiers:[
      { name:"ADULT",      label:"Adult (13+)",        price:45, perks:["Full park access","Unlimited rides","Park map"] },
      { name:"CHILD",      label:"Child (3–12)",        price:32, perks:["Full park access","Unlimited rides","Park map"] },
      { name:"SENIOR",     label:"Senior (60+)",        price:36, perks:["Full park access","Unlimited rides","Park map"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",    price:140,perks:["2 adult + 2 child tickets","Discounted bundle","Park map"] },
      { name:"ANNUAL PASS",label:"Merlin Annual Pass",  price:99, perks:["Unlimited visits all year","15% F&B discount","Guest days","Early entry"] },
    ],
  },
  {
    id:"att-002", cat:"experience", featured:true,
    name:"Warner Bros. Studio Tour London",
    operator:"Warner Bros.",
    city:"London", address:"Studio Tour Dr, Leavesden WD25 7LR",
    hours:"09:00–20:00 (last entry 17:00)", closedOn:"25–26 Dec",
    rating:4.9, reviews:91200,
    image:"https://images.unsplash.com/photo-1503095396549-807759245b35?w=900&h=500&fit=crop&auto=format",
    badge:"Must-See", badgeType:"featured", color:"#a855f7",
    highlights:["Great Hall","Diagon Alley","Flying Ford Anglia","Butterbeer","Platform 9¾","Forbidden Forest"],
    tiers:[
      { name:"ADULT",      label:"Adult (16+)",         price:55, perks:["Studio access","Self-guided tour","Shuttle from Watford Jn."] },
      { name:"CHILD",      label:"Child (5–15)",         price:47, perks:["Studio access","Self-guided tour","Shuttle from Watford Jn."] },
      { name:"TODDLER",    label:"Child under 5",        price:0,  perks:["Free entry (ticket still required)"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",     price:185,perks:["2 adult + 2 child tickets","Bundle saving","Shuttle included"] },
    ],
  },
  {
    id:"att-003", cat:"nature", featured:false,
    name:"ZSL London Zoo",
    operator:"Zoological Society of London",
    city:"London", address:"Outer Cir, Regent's Park, NW1 4RY",
    hours:"10:00–17:30 (last entry 16:00)", closedOn:"25 Dec",
    rating:4.5, reviews:47800,
    image:"https://images.unsplash.com/photo-1604743850414-f613f371d05c?w=900&h=500&fit=crop&auto=format",
    badge:"New Penguin Beach", badgeType:"new", color:"#10b981",
    highlights:["Penguin Beach","Gorilla Kingdom","Tiger Territory","Land of the Lions","Butterfly Paradise","Nightlife"],
    tiers:[
      { name:"ADULT",      label:"Adult (16–64)",       price:28, perks:["Full zoo access","All shows & talks","Guidebook"] },
      { name:"CHILD",      label:"Child (3–15)",         price:18, perks:["Full zoo access","All shows & talks"] },
      { name:"SENIOR",     label:"Senior (65+)",         price:22, perks:["Full zoo access","All shows & talks","Guidebook"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",     price:85, perks:["2 adult + 2 child","Bundle saving","Guidebook"] },
      { name:"ANNUAL",     label:"ZSL Annual Membership",price:95, perks:["Unlimited visits","Whipsnade included","10% shop discount","Member newsletter"] },
    ],
  },
  {
    id:"att-004", cat:"heritage", featured:false,
    name:"Tower of London",
    operator:"Historic Royal Palaces",
    city:"London", address:"Tower Hill, EC3N 4AB",
    hours:"Tue–Sat 09:00–17:30, Sun–Mon 10:00–17:30", closedOn:"24–26 Dec, 1 Jan",
    rating:4.6, reviews:83100,
    image:"https://images.unsplash.com/photo-1513151233558-d860c5398176?w=900&h=500&fit=crop&auto=format",
    badge:"Crown Jewels", badgeType:"featured", color:"#f59e0b",
    highlights:["Crown Jewels exhibition","Yeoman Warder tours","White Tower","Ravens","Medieval Palace","Gift shop"],
    tiers:[
      { name:"ADULT",      label:"Adult (18–59)",       price:29, perks:["Full access","Yeoman tour","Crown Jewels","Audio guide"] },
      { name:"CHILD",      label:"Child (5–17)",         price:15, perks:["Full access","Yeoman tour","Crown Jewels"] },
      { name:"UNDER 5",    label:"Child under 5",        price:0,  perks:["Free entry (ticket required)"] },
      { name:"SENIOR",     label:"Senior (60+)",         price:24, perks:["Full access","Yeoman tour","Crown Jewels","Audio guide"] },
      { name:"FAMILY",     label:"Family (2A + up to 3C)",price:75,perks:["Bundle entry","Yeoman tour","Crown Jewels"] },
    ],
  },
  {
    id:"att-005", cat:"family", featured:false,
    name:"LEGOLAND Windsor Resort",
    operator:"Merlin Entertainments",
    city:"Windsor", address:"Winkfield Rd, Windsor SL4 4AY",
    hours:"10:00–17:00 (seasonal extended hours)", closedOn:"Mon–Fri (term time)",
    rating:4.4, reviews:55900,
    image:"https://images.unsplash.com/photo-1619965258958-7bfbb1bbbb81?w=900&h=500&fit=crop&auto=format",
    badge:"School Hols", badgeType:"urgent", color:"#ef4444",
    highlights:["LEGO City", "Miniland","Dragon Roller Coaster","NINJAGO The Ride","DUPLO Valley","Water Rides"],
    tiers:[
      { name:"ADULT",      label:"Adult (13+)",          price:55, perks:["Full park access","All rides","Park map"] },
      { name:"CHILD",      label:"Child (3–12)",          price:45, perks:["Full park access","All rides","Park map"] },
      { name:"TODDLER",    label:"Child under 3",         price:0,  perks:["Free entry"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",      price:168,perks:["Bundle entry","Saving vs. individual","Park map"] },
      { name:"ANNUAL",     label:"Merlin Annual Pass",    price:99, perks:["Unlimited visits","15% F&B discount","Early entry","Guest days"] },
    ],
  },
  {
    id:"att-006", cat:"museum", featured:false,
    name:"Tate Modern",
    operator:"Tate",
    city:"London", address:"Bankside, SE1 9TG",
    hours:"Sun–Thu 10:00–18:00, Fri–Sat 10:00–22:00", closedOn:"24–26 Dec",
    rating:4.7, reviews:39200,
    image:"https://images.unsplash.com/photo-1606819717115-9159c900370b?w=900&h=500&fit=crop&auto=format",
    badge:"Free Admission", badgeType:"new", color:"#6c5ce7",
    highlights:["Turbine Hall","Permanent Collection","Special Exhibitions","Viewing Level (free)","Tate Eats","Tate Shop"],
    tiers:[
      { name:"GENERAL",    label:"General Admission",    price:0,  perks:["Turbine Hall","Permanent Collection","Viewing Level"] },
      { name:"EXHIBITION", label:"Special Exhibition",   price:22, perks:["Special exhibition entry","Permanent Collection","Viewing Level","Audio guide"] },
      { name:"SUPPORTER",  label:"Tate Supporter",       price:80, perks:["Unlimited exhibitions for 12 months","10% shop discount","Invitations to events","Annual report"] },
    ],
  },
  {
    id:"att-007", cat:"nature", featured:false,
    name:"SEA LIFE London Aquarium",
    operator:"Merlin Entertainments",
    city:"London", address:"County Hall, Westminster Bridge Rd, SE1 7PB",
    hours:"10:00–19:00 (last entry 18:00)", closedOn:"25 Dec",
    rating:4.2, reviews:28700,
    image:"https://images.unsplash.com/photo-1533713692156-f70938dc0d54?w=900&h=500&fit=crop&auto=format",
    badge:"New: Ocean Tunnel", badgeType:"new", color:"#0ea5e9",
    highlights:["14 zones","Glass-bottom boat walk","Shark Walk","Tropical Rainforest","Penguin Point","Touch Pool"],
    tiers:[
      { name:"ADULT",      label:"Adult (16+)",          price:25, perks:["Full aquarium access","All interactive zones"] },
      { name:"CHILD",      label:"Child (3–15)",          price:18, perks:["Full aquarium access","All interactive zones"] },
      { name:"TODDLER",    label:"Child under 3",         price:0,  perks:["Free entry"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",      price:75, perks:["Bundle entry","Saving vs. individual"] },
    ],
  },
  {
    id:"att-008", cat:"nature", featured:false,
    name:"Chester Zoo",
    operator:"Chester Zoo",
    city:"Chester", address:"Caughall Rd, Upton-by-Chester, CH2 1LH",
    hours:"10:00–18:00 (last entry 16:30)", closedOn:"25 Dec",
    rating:4.8, reviews:71300,
    image:"https://images.unsplash.com/photo-1700146134714-f53a41be3cba?w=900&h=500&fit=crop&auto=format",
    badge:"Award Winning", badgeType:"featured", color:"#10b981",
    highlights:["Islands zone","Jaguar trail","Bear Wood","Monkey Forest","Fruit Bat Forest","Conservation fund"],
    tiers:[
      { name:"ADULT",      label:"Adult (16–64)",        price:24, perks:["Full zoo access","All enclosures","Monorail"] },
      { name:"CHILD",      label:"Child (3–15)",          price:18, perks:["Full zoo access","All enclosures","Monorail"] },
      { name:"SENIOR",     label:"Senior (65+)",          price:20, perks:["Full zoo access","All enclosures","Monorail"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",      price:75, perks:["Bundle entry","Saving vs. individual","Monorail"] },
      { name:"ANNUAL",     label:"Chester Zoo Membership",price:85, perks:["Unlimited visits","10% retail discount","Monthly newsletter","Priority booking"] },
    ],
  },
  {
    id:"att-009", cat:"heritage", featured:false,
    name:"Edinburgh Castle",
    operator:"Historic Environment Scotland",
    city:"Edinburgh", address:"Castlehill, Edinburgh EH1 2NG",
    hours:"09:30–18:00 (last entry 17:00)", closedOn:"25–26 Dec",
    rating:4.5, reviews:44800,
    image:"https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=900&h=500&fit=crop&auto=format",
    badge:"UNESCO Site", badgeType:"featured", color:"#f59e0b",
    highlights:["Scottish Crown Jewels","Stone of Destiny","One O'Clock Gun","Great Hall","Royal Palace","Scottish National War Memorial"],
    tiers:[
      { name:"ADULT",      label:"Adult (18–59)",        price:18, perks:["Full castle access","Audio guide","Crown Jewels"] },
      { name:"CHILD",      label:"Child (5–17)",          price:11, perks:["Full castle access","Crown Jewels"] },
      { name:"UNDER 5",    label:"Child under 5",         price:0,  perks:["Free entry"] },
      { name:"SENIOR",     label:"Senior (60+)",          price:14, perks:["Full castle access","Audio guide","Crown Jewels"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",      price:50, perks:["Bundle entry","Audio guide","Crown Jewels"] },
    ],
  },
  {
    id:"att-010", cat:"experience", featured:false,
    name:"Madame Tussauds London",
    operator:"Merlin Entertainments",
    city:"London", address:"Marylebone Rd, NW1 5LR",
    hours:"09:30–17:30 (last entry 15:30)", closedOn:"25 Dec",
    rating:4.1, reviews:34600,
    image:"https://images.unsplash.com/photo-1499762524203-b47f7b1b26a5?w=900&h=500&fit=crop&auto=format",
    badge:"On Sale Now", badgeType:"new", color:"#ec4899",
    highlights:["250+ wax figures","Marvel 4D","Star Wars","Live Music Experience","Sports Zone","Royal Family"],
    tiers:[
      { name:"ADULT",      label:"Adult (16+)",          price:30, perks:["Full attraction access","All zones","Photo opportunities"] },
      { name:"CHILD",      label:"Child (3–15)",          price:24, perks:["Full attraction access","All zones"] },
      { name:"SENIOR",     label:"Senior (60+)",          price:25, perks:["Full attraction access","All zones"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",      price:96, perks:["Bundle entry","Saving vs. individual"] },
    ],
  },
  {
    id:"att-011", cat:"nature", featured:false,
    name:"Eden Project",
    operator:"Eden Project",
    city:"Cornwall", address:"Bodelva, Par, Cornwall PL24 2SG",
    hours:"10:00–18:00 (last entry 16:30)", closedOn:"24–25 Dec",
    rating:4.6, reviews:29400,
    image:"https://images.unsplash.com/photo-1499762524203-b47f7b1b26a5?w=900&h=500&fit=crop&auto=format",
    badge:"Annual Pass Deal", badgeType:"featured", color:"#22c55e",
    highlights:["Rainforest Biome","Mediterranean Biome","Core education centre","Skywire zip wire","Outdoor gardens","Seasonal events"],
    tiers:[
      { name:"ADULT",      label:"Adult (17–59)",        price:28, perks:["Both biomes","Outdoor gardens","Core building"] },
      { name:"CHILD",      label:"Child (5–16)",          price:15, perks:["Both biomes","Outdoor gardens","Core building"] },
      { name:"UNDER 5",    label:"Child under 5",         price:0,  perks:["Free entry"] },
      { name:"SENIOR",     label:"Senior (60+)",          price:22, perks:["Both biomes","Outdoor gardens","Core building"] },
      { name:"ANNUAL",     label:"Eden Annual Pass",      price:55, perks:["Unlimited visits all year","Guest passes","Events access","10% café discount"] },
    ],
  },
  {
    id:"att-012", cat:"theme-park", featured:false,
    name:"Alton Towers Resort",
    operator:"Merlin Entertainments",
    city:"Staffordshire", address:"Alton, Stoke-on-Trent ST10 4DB",
    hours:"10:00–17:00 (extended on peak days)", closedOn:"Mon–Fri (off-peak)",
    rating:4.4, reviews:58100,
    image:"https://images.unsplash.com/photo-1576314728409-e51799b6f849?w=900&h=500&fit=crop&auto=format",
    badge:"Ride Pass Available", badgeType:"new", color:"#f97316",
    highlights:["Nemesis Reborn","Wicker Man","Thirteen","Oblivion","CBeebies Land","Water Park"],
    tiers:[
      { name:"ADULT",      label:"Adult (13+)",          price:50, perks:["Full park access","All rides","Park map"] },
      { name:"CHILD",      label:"Child (3–12)",          price:38, perks:["Full park access","All rides","Park map"] },
      { name:"FAMILY",     label:"Family (2A + 2C)",      price:160,perks:["Bundle entry","Saving vs. individual","Park map"] },
      { name:"ANNUAL",     label:"Merlin Annual Pass",    price:99, perks:["Unlimited visits","15% F&B discount","Early entry","Guest days"] },
    ],
  },
];
